import type { Product, CompletedOrder, PastShift, ShiftData, SyncQueueItem } from "./types";

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    name: "Super Mac",
    category: "mac",
    price: 20000,
    description: "Makaroni keju creamy + chicken katsu + kentang renyah.",
    image: "/assets/menu-super-mac-reference.png",
    isAvailable: true,
    stock: 45,
  },
  {
    id: "prod-2",
    name: "Potato Mac",
    category: "mac",
    price: 15000,
    description: "Makaroni keju creamy bertabur kentang goreng gurih.",
    image: "/assets/menu-potato-mac-reference.png",
    isAvailable: true,
    stock: 38,
  },
  {
    id: "prod-3",
    name: "Classic Mac",
    category: "mac",
    price: 10000,
    description: "Comfort food klasik makaroni dengan lelehan saus keju lembut.",
    image: "/assets/menu-classic-mac-reference.png",
    isAvailable: true,
    stock: 50,
  },
  {
    id: "prod-4",
    name: "Spicy Smokey Mac",
    category: "mac",
    price: 18000,
    description: "Makaroni saus keju dengan aroma smoky dan sensasi pedas mantap.",
    image: "/assets/menu-super-mac-reference.png",
    isAvailable: true,
    stock: 22,
  },
  {
    id: "prod-5",
    name: "Chicken Katsu Ala Carte",
    category: "sides",
    price: 12000,
    description: "Fillet dada ayam krispi berbalut tepung roti renyah keemasan.",
    image: "/assets/menu-chicken-katsu.png",
    isAvailable: true,
    stock: 30,
  },
  {
    id: "prod-6",
    name: "Crispy French Fries",
    category: "sides",
    price: 8000,
    description: "Kentang goreng renyah gurih dengan garam laut halus.",
    image: "/assets/menu-french-fries.png",
    isAvailable: true,
    stock: 40,
  },
  {
    id: "prod-7",
    name: "Es Lemon Tea",
    category: "drinks",
    price: 6000,
    description: "Teh perasan lemon segar asam-manis penghilang dahaga.",
    image: "/assets/menu-es-lemon-tea.png",
    isAvailable: true,
    stock: 60,
  },
  {
    id: "prod-8",
    name: "Es Teh Manis",
    category: "drinks",
    price: 4000,
    description: "Teh melati wangi dingin manis khas MacMood.",
    image: "/assets/menu-es-teh-manis.png",
    isAvailable: true,
    stock: 80,
  },
  {
    id: "prod-9",
    name: "Air Mineral Botol",
    category: "drinks",
    price: 3000,
    description: "Air mineral higienis dingin 600ml.",
    image: "/assets/menu-air-mineral.png",
    isAvailable: true,
    stock: 50,
  },
];

export const INITIAL_ORDERS: CompletedOrder[] = [
  // ===================== HARI INI (26 Sep 2026) - 10 NOTA =====================
  // --- FATMAWATI (5 Nota: 3 Cash, 2 QRIS) ---
  {
    id: "ord-fatmawati-01",
    orderNumber: "MAC-20260926-1001",
    branchId: "branch-1",
    branchName: "MacMood Pusat - Fatmawati",
    items: [
      { productId: "prod-1", name: "Super Mac", quantity: 2, price: 20000, subtotal: 40000, notes: "Extra saus keju" },
      { productId: "prod-7", name: "Es Lemon Tea", quantity: 2, price: 6000, subtotal: 12000 },
    ],
    subtotal: 52000,
    tax: 5200,
    total: 57200,
    paymentMethod: "CASH",
    amountTendered: 60000,
    change: 2800,
    timestamp: "08:30 WIB",
    dateStr: "2026-09-26",
    cashierName: "Kasir Fatmawati",
    syncStatus: "SYNCED",
    status: "PAID",
  },
  {
    id: "ord-fatmawati-02",
    orderNumber: "MAC-20260926-1002",
    branchId: "branch-1",
    branchName: "MacMood Pusat - Fatmawati",
    items: [
      { productId: "prod-2", name: "Potato Mac", quantity: 1, price: 15000, subtotal: 15000 },
      { productId: "prod-6", name: "Crispy French Fries", quantity: 1, price: 8000, subtotal: 8000 },
      { productId: "prod-8", name: "Es Teh Manis", quantity: 1, price: 4000, subtotal: 4000 },
    ],
    subtotal: 27000,
    tax: 2700,
    total: 29700,
    paymentMethod: "QRIS_MANUAL",
    amountTendered: 29700,
    change: 0,
    timestamp: "09:15 WIB",
    dateStr: "2026-09-26",
    cashierName: "Kasir Fatmawati",
    syncStatus: "SYNCED",
    status: "PAID",
  },
  {
    id: "ord-fatmawati-03",
    orderNumber: "MAC-20260926-1003",
    branchId: "branch-1",
    branchName: "MacMood Pusat - Fatmawati",
    items: [
      { productId: "prod-4", name: "Spicy Smokey Mac", quantity: 1, price: 18000, subtotal: 18000, notes: "Pedas mantap" },
      { productId: "prod-5", name: "Chicken Katsu Ala Carte", quantity: 1, price: 12000, subtotal: 12000 },
      { productId: "prod-7", name: "Es Lemon Tea", quantity: 1, price: 6000, subtotal: 6000 },
    ],
    subtotal: 36000,
    tax: 3600,
    total: 39600,
    paymentMethod: "CASH",
    amountTendered: 50000,
    change: 10400,
    timestamp: "10:20 WIB",
    dateStr: "2026-09-26",
    cashierName: "Kasir Fatmawati",
    syncStatus: "SYNCED",
    status: "PAID",
  },
  {
    id: "ord-fatmawati-04",
    orderNumber: "MAC-20260926-1004",
    branchId: "branch-1",
    branchName: "MacMood Pusat - Fatmawati",
    items: [
      { productId: "prod-3", name: "Classic Mac", quantity: 2, price: 10000, subtotal: 20000 },
      { productId: "prod-8", name: "Es Teh Manis", quantity: 2, price: 4000, subtotal: 8000 },
    ],
    subtotal: 28000,
    tax: 2800,
    total: 30800,
    paymentMethod: "QRIS_MANUAL",
    amountTendered: 30800,
    change: 0,
    timestamp: "11:45 WIB",
    dateStr: "2026-09-26",
    cashierName: "Kasir Fatmawati",
    syncStatus: "SYNCED",
    status: "PAID",
  },
  {
    id: "ord-fatmawati-05",
    orderNumber: "MAC-20260926-1005",
    branchId: "branch-1",
    branchName: "MacMood Pusat - Fatmawati",
    items: [
      { productId: "prod-1", name: "Super Mac", quantity: 2, price: 20000, subtotal: 40000 },
      { productId: "prod-6", name: "Crispy French Fries", quantity: 1, price: 8000, subtotal: 8000 },
      { productId: "prod-7", name: "Es Lemon Tea", quantity: 2, price: 6000, subtotal: 12000 },
    ],
    subtotal: 60000,
    discount: 6000,
    promoCode: "MACMOOD10",
    promoName: "Promo Opening Mac & Cheese 10%",
    tax: 5400,
    total: 59400,
    paymentMethod: "CASH",
    amountTendered: 100000,
    change: 40600,
    timestamp: "12:30 WIB",
    dateStr: "2026-09-26",
    cashierName: "Kasir Fatmawati",
    syncStatus: "SYNCED",
    status: "PAID",
  },

  // --- MARGONDA (3 Nota: 2 Cash, 1 QRIS) ---
  {
    id: "ord-margonda-01",
    orderNumber: "MAC-20260926-2001",
    branchId: "branch-2",
    branchName: "MacMood Express - Margonda",
    items: [
      { productId: "prod-2", name: "Potato Mac", quantity: 2, price: 15000, subtotal: 30000 },
      { productId: "prod-8", name: "Es Teh Manis", quantity: 2, price: 4000, subtotal: 8000 },
    ],
    subtotal: 38000,
    tax: 3800,
    total: 41800,
    paymentMethod: "CASH",
    amountTendered: 50000,
    change: 8200,
    timestamp: "09:40 WIB",
    dateStr: "2026-09-26",
    cashierName: "Kasir Margonda",
    syncStatus: "SYNCED",
    status: "PAID",
  },
  {
    id: "ord-margonda-02",
    orderNumber: "MAC-20260926-2002",
    branchId: "branch-2",
    branchName: "MacMood Express - Margonda",
    items: [
      { productId: "prod-1", name: "Super Mac", quantity: 1, price: 20000, subtotal: 20000 },
      { productId: "prod-5", name: "Chicken Katsu Ala Carte", quantity: 1, price: 12000, subtotal: 12000 },
      { productId: "prod-9", name: "Air Mineral Botol", quantity: 1, price: 3000, subtotal: 3000 },
    ],
    subtotal: 35000,
    tax: 3500,
    total: 38500,
    paymentMethod: "QRIS_MANUAL",
    amountTendered: 38500,
    change: 0,
    timestamp: "10:50 WIB",
    dateStr: "2026-09-26",
    cashierName: "Kasir Margonda",
    syncStatus: "SYNCED",
    status: "PAID",
  },
  {
    id: "ord-margonda-03",
    orderNumber: "MAC-20260926-2003",
    branchId: "branch-2",
    branchName: "MacMood Express - Margonda",
    items: [
      { productId: "prod-4", name: "Spicy Smokey Mac", quantity: 2, price: 18000, subtotal: 36000 },
      { productId: "prod-6", name: "Crispy French Fries", quantity: 1, price: 8000, subtotal: 8000 },
      { productId: "prod-8", name: "Es Teh Manis", quantity: 2, price: 4000, subtotal: 8000 },
    ],
    subtotal: 52000,
    tax: 5200,
    total: 57200,
    paymentMethod: "CASH",
    amountTendered: 60000,
    change: 2800,
    timestamp: "12:15 WIB",
    dateStr: "2026-09-26",
    cashierName: "Kasir Margonda",
    syncStatus: "SYNCED",
    status: "PAID",
  },

  // --- TEBET (2 Nota: 1 Cash, 1 QRIS) ---
  {
    id: "ord-tebet-01",
    orderNumber: "MAC-20260926-3001",
    branchId: "branch-3",
    branchName: "MacMood Kitchen - Tebet",
    items: [
      { productId: "prod-3", name: "Classic Mac", quantity: 3, price: 10000, subtotal: 30000 },
      { productId: "prod-8", name: "Es Teh Manis", quantity: 3, price: 4000, subtotal: 12000 },
    ],
    subtotal: 42000,
    tax: 4200,
    total: 46200,
    paymentMethod: "QRIS_MANUAL",
    amountTendered: 46200,
    change: 0,
    timestamp: "10:10 WIB",
    dateStr: "2026-09-26",
    cashierName: "Kasir Tebet",
    syncStatus: "SYNCED",
    status: "PAID",
  },
  {
    id: "ord-tebet-02",
    orderNumber: "MAC-20260926-3002",
    branchId: "branch-3",
    branchName: "MacMood Kitchen - Tebet",
    items: [
      { productId: "prod-1", name: "Super Mac", quantity: 2, price: 20000, subtotal: 40000 },
      { productId: "prod-6", name: "Crispy French Fries", quantity: 1, price: 8000, subtotal: 8000 },
      { productId: "prod-7", name: "Es Lemon Tea", quantity: 2, price: 6000, subtotal: 12000 },
    ],
    subtotal: 60000,
    tax: 6000,
    total: 66000,
    paymentMethod: "CASH",
    amountTendered: 70000,
    change: 4000,
    timestamp: "11:25 WIB",
    dateStr: "2026-09-26",
    cashierName: "Kasir Tebet",
    syncStatus: "SYNCED",
    status: "PAID",
  },
];

export const INITIAL_SHIFT: ShiftData = {
  id: "shift-20260926-01",
  status: "OPEN",
  cashierName: "Kasir Fatmawati",
  startTime: "08:00 WIB",
  initialCash: 200000,
  cashSales: 156200,
  qrisSales: 60500,
  orderCount: 5,
  expectedCash: 332200,
  actualCash: 332200,
  cashDifference: 0,
  notes: "Shift pagi Fatmawati beroperasi normal.",
};

export const INITIAL_PAST_SHIFTS: PastShift[] = [
  {
    id: "shift-20260925-02",
    date: "25 September 2026",
    cashierName: "Kasir Margonda",
    shiftName: "Shift Malam",
    startTime: "15:00 WIB",
    endTime: "22:00 WIB",
    initialCash: 150000,
    cashSales: 840000,
    qrisSales: 620000,
    expectedCash: 990000,
    actualCash: 990000,
    cashDifference: 0,
    status: "CLOSED",
    notes: "Semua laci fisik klop tanpa selisih.",
  },
  {
    id: "shift-20260925-01",
    date: "25 September 2026",
    cashierName: "Kasir Fatmawati",
    shiftName: "Shift Pagi",
    startTime: "08:00 WIB",
    endTime: "15:00 WIB",
    initialCash: 200000,
    cashSales: 910000,
    qrisSales: 550000,
    expectedCash: 1110000,
    actualCash: 1110000,
    cashDifference: 0,
    status: "CLOSED",
    notes: "Operasional ramai saat jam makan siang.",
  },
];

export const INITIAL_SYNC_QUEUE: SyncQueueItem[] = [];
