import type {
  AdminProduct,
  StockLog,
  StaffAccount,
  OutletSettings,
  ShiftRecord,
  ExpenseRecord,
  AuditLogRecord,
  PromoVoucher,
  RawMaterial,
  ProductRecipe,
  BranchOutlet,
} from "./types";

export const INITIAL_ADMIN_PRODUCTS: AdminProduct[] = [
  {
    id: "prod-1",
    name: "Super Mac",
    category: "mac",
    categoryLabel: "Mac & Cheese",
    price: 20000,
    costPrice: 9500,
    description: "Makaroni keju creamy + chicken katsu + kentang renyah.",
    image: "/assets/menu-super-mac-reference.png",
    isAvailable: true,
    trackStock: true,
    currentStock: 105,
    branchStocks: { "branch-1": 45, "branch-2": 32, "branch-3": 28 },
    lowStockThreshold: 20,
    soldCount: 82,
  },
  {
    id: "prod-2",
    name: "Potato Mac",
    category: "mac",
    categoryLabel: "Mac & Cheese",
    price: 15000,
    costPrice: 7000,
    description: "Makaroni keju creamy bertabur kentang goreng gurih.",
    image: "/assets/menu-potato-mac-reference.png",
    isAvailable: true,
    trackStock: true,
    currentStock: 85,
    branchStocks: { "branch-1": 38, "branch-2": 25, "branch-3": 22 },
    lowStockThreshold: 20,
    soldCount: 45,
  },
  {
    id: "prod-3",
    name: "Classic Mac",
    category: "mac",
    categoryLabel: "Mac & Cheese",
    price: 10000,
    costPrice: 4800,
    description:
      "Comfort food klasik makaroni dengan lelehan saus keju lembut.",
    image: "/assets/menu-classic-mac-reference.png",
    isAvailable: true,
    trackStock: true,
    currentStock: 110,
    branchStocks: { "branch-1": 50, "branch-2": 35, "branch-3": 25 },
    lowStockThreshold: 20,
    soldCount: 27,
  },
  {
    id: "prod-4",
    name: "Spicy Smokey Mac",
    category: "mac",
    categoryLabel: "Mac & Cheese",
    price: 18000,
    costPrice: 8500,
    description:
      "Makaroni saus keju dengan aroma smoky dan sensasi pedas mantap.",
    image: "/assets/menu-super-mac-reference.png",
    isAvailable: true,
    trackStock: true,
    currentStock: 52,
    branchStocks: { "branch-1": 14, "branch-2": 20, "branch-3": 18 },
    lowStockThreshold: 20,
    soldCount: 39,
  },
  {
    id: "prod-5",
    name: "Chicken Katsu Ala Carte",
    category: "sides",
    categoryLabel: "Add-on",
    price: 12000,
    costPrice: 5500,
    description:
      "Fillet dada ayam krispi berbalut tepung roti renyah keemasan.",
    image: "/assets/menu-chicken-katsu.png",
    isAvailable: true,
    trackStock: true,
    currentStock: 75,
    branchStocks: { "branch-1": 30, "branch-2": 25, "branch-3": 20 },
    lowStockThreshold: 15,
    soldCount: 32,
  },
  {
    id: "prod-6",
    name: "Crispy French Fries",
    category: "sides",
    categoryLabel: "Add-on",
    price: 8000,
    costPrice: 3200,
    description: "Kentang goreng renyah gurih dengan garam laut halus.",
    image: "/assets/menu-french-fries.png",
    isAvailable: true,
    trackStock: true,
    currentStock: 95,
    branchStocks: { "branch-1": 40, "branch-2": 30, "branch-3": 25 },
    lowStockThreshold: 15,
    soldCount: 51,
  },
  {
    id: "prod-7",
    name: "Es Lemon Tea",
    category: "drinks",
    categoryLabel: "Minuman",
    price: 6000,
    costPrice: 2000,
    description: "Teh perasan lemon segar asam-manis penghilang dahaga.",
    image: "/assets/menu-es-lemon-tea.png",
    isAvailable: true,
    trackStock: true,
    currentStock: 140,
    branchStocks: { "branch-1": 60, "branch-2": 45, "branch-3": 35 },
    lowStockThreshold: 20,
    soldCount: 68,
  },
  {
    id: "prod-8",
    name: "Es Teh Manis",
    category: "drinks",
    categoryLabel: "Minuman",
    price: 4000,
    costPrice: 1200,
    description: "Teh melati wangi dingin manis khas MacMood.",
    image: "/assets/menu-es-teh-manis.png",
    isAvailable: true,
    trackStock: true,
    currentStock: 190,
    branchStocks: { "branch-1": 80, "branch-2": 60, "branch-3": 50 },
    lowStockThreshold: 25,
    soldCount: 74,
  },
  {
    id: "prod-9",
    name: "Air Mineral Botol",
    category: "drinks",
    categoryLabel: "Minuman",
    price: 3000,
    costPrice: 1500,
    description: "Air mineral higienis dingin 600ml.",
    image: "/assets/menu-air-mineral.png",
    isAvailable: true,
    trackStock: true,
    currentStock: 120,
    branchStocks: { "branch-1": 50, "branch-2": 40, "branch-3": 30 },
    lowStockThreshold: 20,
    soldCount: 33,
  },
];

export const INITIAL_STOCK_LOGS: StockLog[] = [
  {
    id: "log-1",
    productId: "prod-4",
    productName: "Spicy Smokey Mac",
    quantityChange: -5,
    finalStock: 14,
    reason: "SPOILAGE",
    reasonLabel: "Bahan Rusak / Basi",
    notes: "Ditemukan saus bumbu pasta menggumpal saat persiapan pagi.",
    staffName: "Budi Santoso",
    timestamp: "24 Sep 2026, 08:30 WIB",
  },
  {
    id: "log-2",
    productId: "prod-1",
    productName: "Super Mac",
    quantityChange: 50,
    finalStock: 45,
    reason: "RESTOCK",
    reasonLabel: "Restock Bahan Masuk",
    notes: "Kiriman batch katsu dan makaroni dari dapur pusat.",
    staffName: "Muhammad Afrizal (Owner)",
    timestamp: "24 Sep 2026, 07:15 WIB",
  },
  {
    id: "log-3",
    productId: "prod-6",
    productName: "Crispy French Fries",
    quantityChange: 30,
    finalStock: 40,
    reason: "RESTOCK",
    reasonLabel: "Restock Bahan Masuk",
    notes: "Restock kentang beku 10kg.",
    staffName: "Muhammad Afrizal (Owner)",
    timestamp: "23 Sep 2026, 14:00 WIB",
  },
  {
    id: "log-4",
    productId: "prod-3",
    productName: "Classic Mac",
    quantityChange: -2,
    finalStock: 50,
    reason: "ADJUSTMENT",
    reasonLabel: "Penyesuaian Opname",
    notes: "Koreksi selisih hitung fisik saat penutupan shift malam.",
    staffName: "Siti Rahma",
    timestamp: "23 Sep 2026, 22:10 WIB",
  },
];

export const INITIAL_BRANCHES: BranchOutlet[] = [
  {
    id: "branch-1",
    name: "MacMood Pusat - Fatmawati",
    branchCode: "MAC-JKT-01",
    code: "MAC-JKT-01",
    address: "Jl. RS Fatmawati Raya No. 18, Cilandak",
    city: "Jakarta Selatan",
    phone: "+62 812-3456-7890",
    email: "fatmawati@macmood.id",
    pin: "1234",
    isActive: true,
    openedAt: "12 Januari 2026",
    taxRate: 10,
    serviceChargeRate: 0,
    qrisMerchantName: "MACMOOD FOOD INDONESIA",
    qrisNmid: "ID102008899201",
    bankAccount: "8830192841",
    bankName: "BCA",
  },
  {
    id: "branch-2",
    name: "MacMood Express - Margonda",
    branchCode: "MAC-DPK-01",
    code: "MAC-DPK-01",
    address: "Jl. Margonda Raya No. 120, Beji",
    city: "Depok",
    phone: "+62 812-9876-5432",
    email: "margonda@macmood.id",
    pin: "5678",
    isActive: true,
    openedAt: "1 Mei 2026",
    taxRate: 10,
    serviceChargeRate: 0,
    qrisMerchantName: "MACMOOD EXPRESS MARGONDA",
    qrisNmid: "ID102008899202",
    bankAccount: "8830192842",
    bankName: "BCA",
  },
  {
    id: "branch-3",
    name: "MacMood Kitchen - Tebet",
    branchCode: "MAC-JKT-02",
    code: "MAC-JKT-02",
    address: "Jl. Tebet Timur Dalam Raya No. 45",
    city: "Jakarta Selatan",
    phone: "+62 812-1122-3344",
    email: "tebet@macmood.id",
    pin: "9012",
    isActive: true,
    openedAt: "15 Juli 2026",
    taxRate: 10,
    serviceChargeRate: 0,
    qrisMerchantName: "MACMOOD KITCHEN TEBET",
    qrisNmid: "ID102008899203",
    bankAccount: "8830192843",
    bankName: "BCA",
  },
];

export const INITIAL_STAFF_ACCOUNTS: StaffAccount[] = [
  {
    id: "staff-1",
    name: "Muhammad Afrizal",
    email: "owner@macmood.id",
    role: "owner",
    pin: "8899",
    branchId: "branch-1",
    branchName: "Akses Global (Semua Cabang)",
    isActive: true,
    lastLogin: "26 Sep 2026, 08:00 WIB",
  },
  {
    id: "staff-2",
    name: "Akun Cabang Fatmawati",
    email: "fatmawati@macmood.id",
    role: "cashier",
    pin: "1234",
    branchId: "branch-1",
    branchName: "MacMood Pusat - Fatmawati",
    isActive: true,
    lastLogin: "26 Sep 2026, 08:05 WIB",
  },
  {
    id: "staff-3",
    name: "Akun Cabang Margonda",
    email: "margonda@macmood.id",
    role: "cashier",
    pin: "5678",
    branchId: "branch-2",
    branchName: "MacMood Express - Margonda",
    isActive: true,
    lastLogin: "26 Sep 2026, 08:30 WIB",
  },
  {
    id: "staff-4",
    name: "Akun Cabang Tebet",
    email: "tebet@macmood.id",
    role: "cashier",
    pin: "9012",
    branchId: "branch-3",
    branchName: "MacMood Kitchen - Tebet",
    isActive: true,
    lastLogin: "26 Sep 2026, 09:00 WIB",
  },
];

export const INITIAL_OUTLET_SETTINGS: OutletSettings = {
  name: "MacMood Indonesia (PT MacMood Kuliner Nusantara)",
  branchCode: "MAC-HQ-01",
  address: "Jl. RS Fatmawati Raya No. 18, Cilandak",
  city: "Jakarta Selatan",
  phone: "+62 812-3456-7890",
  timezone: "Asia/Jakarta (WIB)",
  taxRate: 10, // 10% PB1 Restoran
  serviceChargeRate: 0,
  qrisMerchantName: "MACMOOD FOOD INDONESIA",
  qrisNmid: "ID102008899201",
  bankAccount: "8830192841",
  bankName: "Bank Central Asia (BCA)",
};

// -------------------------------------------------------------
// Initial Mock Data: Rekapitulasi Riwayat Shift Kasir (PRD)
// -------------------------------------------------------------
export const INITIAL_SHIFTS: ShiftRecord[] = [
  {
    id: "shift-20260926-01",
    shiftName: "Shift Pagi · Pusat Fatmawati",
    branchId: "branch-1",
    branchName: "MacMood Pusat - Fatmawati",
    branchCode: "MAC-JKT-01",
    cashierId: "staff-2",
    cashierName: "Kasir Fatmawati",
    startTime: "08:00 WIB",
    endTime: null,
    date: "26 Sep 2026",
    initialCash: 200000,
    cashSales: 156200,
    qrisSales: 60500,
    totalOrders: 5,
    expectedCash: 332200,
    actualCash: 332200,
    cashDifference: 0,
    status: "OPEN",
    notes: "Shift pagi cabang pusat Fatmawati berjalan lancar.",
    verifiedByOwner: false,
  },
  {
    id: "shift-20260926-02",
    shiftName: "Shift Pagi · Express Margonda",
    branchId: "branch-2",
    branchName: "MacMood Express - Margonda",
    branchCode: "MAC-DPK-01",
    cashierId: "staff-3",
    cashierName: "Kasir Margonda",
    startTime: "08:30 WIB",
    endTime: null,
    date: "26 Sep 2026",
    initialCash: 150000,
    cashSales: 99000,
    qrisSales: 38500,
    totalOrders: 3,
    expectedCash: 226000,
    actualCash: 226000,
    cashDifference: 0,
    status: "OPEN",
    notes: "Shift pagi cabang Margonda Depok siap melayani.",
    verifiedByOwner: false,
  },
  {
    id: "shift-20260926-03",
    shiftName: "Shift Pagi · Kitchen Tebet",
    branchId: "branch-3",
    branchName: "MacMood Kitchen - Tebet",
    branchCode: "MAC-JKT-02",
    cashierId: "staff-4",
    cashierName: "Kasir Tebet",
    startTime: "09:00 WIB",
    endTime: null,
    date: "26 Sep 2026",
    initialCash: 150000,
    cashSales: 66000,
    qrisSales: 46200,
    totalOrders: 2,
    expectedCash: 216000,
    actualCash: 216000,
    cashDifference: 0,
    status: "OPEN",
    notes: "Shift pagi cabang Tebet Timur melayani takeaway.",
    verifiedByOwner: false,
  },
];

// -------------------------------------------------------------
// Initial Mock Data: Pengeluaran Kas Kecil / Biaya Operasional (PRD Fase 2)
// -------------------------------------------------------------
export const INITIAL_EXPENSES: ExpenseRecord[] = [
  {
    id: "exp-20260926-01",
    date: "26 Sep 2026",
    time: "09:30 WIB",
    category: "BAHAN_BAKU",
    categoryLabel: "Bahan Baku & Es Batu",
    description: "Es Batu Kristal Higienis 2 Bal",
    amount: 24000,
    sourceOfFund: "KAS_LACI",
    staffName: "Kasir Fatmawati",
    notes:
      "Kebutuhan es batu mendesak untuk es teh & lemon tea cabang Fatmawati",
    receiptNumber: "NOTA-ES-882",
  },
  {
    id: "exp-20260926-02",
    date: "26 Sep 2026",
    time: "11:00 WIB",
    category: "UTILITAS_GAS",
    categoryLabel: "Gas LPG & Listrik",
    description: "Isi Ulang Gas LPG 3kg",
    amount: 23000,
    sourceOfFund: "KAS_LACI",
    staffName: "Kasir Margonda",
    notes: "Penggantian tabung kompor memasak makaroni Margonda",
    receiptNumber: "GAS-MRG-102",
  },
  {
    id: "exp-20260926-03",
    date: "26 Sep 2026",
    time: "12:00 WIB",
    category: "KEMASAN",
    categoryLabel: "Kemasan & Kantong",
    description: "Kantong Kresek Takeaway Ramah Lingkungan",
    amount: 35000,
    sourceOfFund: "TRANSFER_OWNER",
    staffName: "Muhammad Afrizal (Owner)",
    notes: "Restock kemasan takeaway langsung ditransfer oleh Owner",
    receiptNumber: "INV-PLASTIK-44",
  },
];

// -------------------------------------------------------------
// Initial Mock Data: Log Audit Keamanan & Sistem (PRD)
// -------------------------------------------------------------
export const INITIAL_AUDIT_LOGS: AuditLogRecord[] = [
  {
    id: "audit-20260924-01",
    timestamp: "24 Sep 2026, 09:15 WIB",
    date: "24 Sep 2026",
    time: "09:15 WIB",
    action: "MENU_PRICE_CHANGE",
    actionLabel: "Perubahan Harga Menu",
    entityType: "PRODUCT",
    entityId: "prod-1",
    performedBy: "Muhammad Afrizal",
    userRole: "owner",
    details: {
      title: "Penyesuaian Harga Jual Menu Super Mac",
      before: "Rp 18.000 (Margin 47.2%)",
      after: "Rp 20.000 (Margin 52.5%)",
      reason: "Penyesuaian kenaikan harga keju cheddar impor dan kemasan baru",
    },
  },
  {
    id: "audit-20260924-02",
    timestamp: "24 Sep 2026, 09:20 WIB",
    date: "24 Sep 2026",
    time: "09:20 WIB",
    action: "VOID_ORDER",
    actionLabel: "Otorisasi Void Transaksi",
    entityType: "ORDER",
    entityId: "MAC-20260924-004",
    performedBy: "Muhammad Afrizal",
    userRole: "owner",
    details: {
      title: "Pembatalan Nota Transaksi #MAC-20260924-004",
      before: "Status: PAID (Rp 30.800 - Tunai)",
      after: "Status: VOID (Pengembalian Dana Kasir)",
      reason:
        "Pelanggan salah pesan varian dan minta diganti sebelum makanan diproses dapur",
    },
  },
  {
    id: "audit-20260923-01",
    timestamp: "23 Sep 2026, 16:05 WIB",
    date: "23 Sep 2026",
    time: "16:05 WIB",
    action: "STAFF_PIN_RESET",
    actionLabel: "Reset PIN Staf Kasir",
    entityType: "STAFF",
    entityId: "staff-2",
    performedBy: "Muhammad Afrizal",
    userRole: "owner",
    details: {
      title: "Reset PIN Kasir Outlet 1 · Fatmawati",
      before: "PIN Lama Aktif",
      after: "PIN Baru Aktif (1234)",
      reason: "Rotasi keamanan berkala password dan PIN operasional kasir",
    },
  },
  {
    id: "audit-20260923-02",
    timestamp: "23 Sep 2026, 22:35 WIB",
    date: "23 Sep 2026",
    time: "22:35 WIB",
    action: "SHIFT_FORCE_CLOSE",
    actionLabel: "Verifikasi Shift Kasir",
    entityType: "SHIFT",
    entityId: "shift-20260923-02",
    performedBy: "Muhammad Afrizal",
    userRole: "owner",
    details: {
      title: "Verifikasi & Approval Rekonsiliasi Kas Shift Sore Margonda",
      before: "Expected Cash: Rp 2.120.000",
      after: "Actual Cash: Rp 2.120.000 (Selisih Rp0)",
      reason: "Shift tuntas ditutup, uang kas disetor ke brankas outlet",
    },
  },
  {
    id: "audit-20260923-03",
    timestamp: "23 Sep 2026, 14:30 WIB",
    date: "23 Sep 2026",
    time: "14:30 WIB",
    action: "EXPENSE_RECORDED",
    actionLabel: "Pencatatan Biaya Kas Kecil",
    entityType: "EXPENSE",
    entityId: "exp-20260923-01",
    performedBy: "Kasir Outlet 2 · Margonda",
    userRole: "cashier",
    details: {
      title: "Pengeluaran Kas Laci Rp 45.000",
      before: "Saldo Kas Laci: Rp 1.150.000",
      after: "Saldo Kas Laci: Rp 1.105.000",
      reason:
        "Beli kantong plastik kresek ramah lingkungan MacMood di toko terdekat",
    },
  },
];

// -------------------------------------------------------------
// Initial Mock Data: Diskon, Voucher & Promo Dinamis (PRD Fase 2)
// -------------------------------------------------------------
export const INITIAL_PROMOS: PromoVoucher[] = [
  {
    id: "promo-1",
    code: "MACMOOD10",
    name: "Diskon Peluncuran 10%",
    discountType: "PERCENTAGE",
    discountValue: 10,
    maxDiscount: 15000,
    minOrderAmount: 30000,
    quota: 100,
    usedCount: 24,
    startDate: "2026-09-01",
    endDate: "2026-10-31",
    isActive: true,
    description:
      "Diskon 10% untuk semua menu dengan minimal transaksi Rp 30.000 (Maks. Rp 15.000).",
  },
  {
    id: "promo-2",
    code: "HEMAT5K",
    name: "Potongan Langsung Rp 5.000",
    discountType: "FIXED_AMOUNT",
    discountValue: 5000,
    minOrderAmount: 40000,
    quota: 50,
    usedCount: 18,
    startDate: "2026-09-10",
    endDate: "2026-10-15",
    isActive: true,
    description:
      "Potongan harga langsung Rp 5.000 untuk pembelian minimal Rp 40.000.",
  },
  {
    id: "promo-3",
    code: "JUMATBERKAH",
    name: "Promo Spesial Jumat 15%",
    discountType: "PERCENTAGE",
    discountValue: 15,
    maxDiscount: 20000,
    minOrderAmount: 35000,
    quota: 75,
    usedCount: 31,
    startDate: "2026-09-05",
    endDate: "2026-11-30",
    isActive: true,
    description: "Diskon 15% setiap Jumat untuk kumpul bareng teman/keluarga.",
  },
  {
    id: "promo-4",
    code: "BFFCOMBO",
    name: "Voucher Pesta Mac Ramean",
    discountType: "FIXED_AMOUNT",
    discountValue: 10000,
    minOrderAmount: 75000,
    quota: 40,
    usedCount: 9,
    startDate: "2026-09-15",
    endDate: "2026-10-25",
    isActive: true,
    description:
      "Potongan Rp 10.000 khusus pembelian combo party minimal Rp 75.000.",
  },
  {
    id: "promo-5",
    code: "PELAJAR15",
    name: "Diskon Pelajar / Mahasiswa",
    discountType: "PERCENTAGE",
    discountValue: 15,
    maxDiscount: 10000,
    minOrderAmount: 25000,
    quota: 200,
    usedCount: 67,
    startDate: "2026-09-01",
    endDate: "2026-12-31",
    isActive: true,
    description:
      "Tunjukkan kartu pelajar/mahasiswa untuk menikmati diskon 15% (Maks. Rp 10.000).",
  },
  {
    id: "promo-6",
    code: "FLASHDEAL8K",
    name: "Flash Sale Eksklusif",
    discountType: "FIXED_AMOUNT",
    discountValue: 8000,
    minOrderAmount: 50000,
    quota: 30,
    usedCount: 30,
    startDate: "2026-08-01",
    endDate: "2026-08-31",
    isActive: false,
    description:
      "Promo flash sale periode bulan lalu yang sudah non-aktif / kuota habis.",
  },
];

// -------------------------------------------------------------------------
// Initial Mock Data: Bahan Baku Mentah (Raw Materials - PRD Fase 2)
// -------------------------------------------------------------------------
export const INITIAL_RAW_MATERIALS: RawMaterial[] = [
  {
    id: "rm-1",
    code: "RM-MAC-01",
    name: "Makaroni Elbow Kering (Grade A)",
    category: "PASTA",
    categoryLabel: "Pasta Mentah",
    currentStock: 14500, // 14.5 kg
    unit: "gram",
    minThreshold: 3000,
    costPerUnit: 32, // Rp 32/g (Rp 32.000/kg)
    supplier: "PT Bogasari Flour Mills",
    lastRestockDate: "23 Sep 2026",
  },
  {
    id: "rm-2",
    code: "RM-CHD-01",
    name: "Keju Cheddar Olahan Melt",
    category: "DAIRY_CHEESE",
    categoryLabel: "Keju & Susu",
    currentStock: 6800, // 6.8 kg
    unit: "gram",
    minThreshold: 1500,
    costPerUnit: 98, // Rp 98/g
    supplier: "Kraft Pro Foodservice",
    lastRestockDate: "22 Sep 2026",
  },
  {
    id: "rm-3",
    code: "RM-MOZ-01",
    name: "Keju Mozzarella Shredded (Melt)",
    category: "DAIRY_CHEESE",
    categoryLabel: "Keju & Susu",
    currentStock: 4200, // 4.2 kg
    unit: "gram",
    minThreshold: 1200,
    costPerUnit: 135, // Rp 135/g
    supplier: "Anchor Dairy Foodservice",
    lastRestockDate: "22 Sep 2026",
  },
  {
    id: "rm-4",
    code: "RM-CRM-01",
    name: "Cooking Cream / Susu Evaporasi",
    category: "DAIRY_CHEESE",
    categoryLabel: "Keju & Susu",
    currentStock: 5500, // 5.5 Liter
    unit: "ml",
    minThreshold: 1500,
    costPerUnit: 42, // Rp 42/ml
    supplier: "Diamond Dairy Indonesia",
    lastRestockDate: "23 Sep 2026",
  },
  {
    id: "rm-5",
    code: "RM-KTS-01",
    name: "Dada Ayam Fillet Marinated (Katsu Prep)",
    category: "PROTEIN",
    categoryLabel: "Daging & Protein",
    currentStock: 3500, // 3.5 kg
    unit: "gram",
    minThreshold: 800,
    costPerUnit: 68, // Rp 68/g
    supplier: "RPU Berkah Unggas",
    lastRestockDate: "24 Sep 2026",
  },
  {
    id: "rm-6",
    code: "RM-POT-01",
    name: "Kentang French Fries Shoestring Frozen",
    category: "PROTEIN",
    categoryLabel: "Daging & Protein",
    currentStock: 5200, // 5.2 kg
    unit: "gram",
    minThreshold: 1200,
    costPerUnit: 45, // Rp 45/g
    supplier: "Lutosa Fries Import",
    lastRestockDate: "21 Sep 2026",
  },
  {
    id: "rm-7",
    code: "RM-TEA-01",
    name: "Daun Teh Melati Premium Loose",
    category: "SEASONING",
    categoryLabel: "Bumbu & Minuman",
    currentStock: 2400,
    unit: "gram",
    minThreshold: 500,
    costPerUnit: 25, // Rp 25/g
    supplier: "Tong Tji Supply Heritage",
    lastRestockDate: "20 Sep 2026",
  },
  {
    id: "rm-8",
    code: "RM-LMN-01",
    name: "Sari Lemon Murni Concentrate",
    category: "SEASONING",
    categoryLabel: "Bumbu & Minuman",
    currentStock: 1800,
    unit: "ml",
    minThreshold: 400,
    costPerUnit: 35, // Rp 35/ml
    supplier: "Citrus Alam Nusantara",
    lastRestockDate: "20 Sep 2026",
  },
  {
    id: "rm-9",
    code: "RM-BOX-01",
    name: "Paper Box MacMood Signature Brown Kraft",
    category: "PACKAGING",
    categoryLabel: "Kemasan & Packaging",
    currentStock: 480,
    unit: "pcs",
    minThreshold: 100,
    costPerUnit: 850, // Rp 850/pc
    supplier: "Percetakan Kemasan Jaya",
    lastRestockDate: "23 Sep 2026",
  },
  {
    id: "rm-10",
    code: "RM-CUT-01",
    name: "Sendok & Garpu Kayu Disposable",
    category: "PACKAGING",
    categoryLabel: "Kemasan & Packaging",
    currentStock: 520,
    unit: "pcs",
    minThreshold: 100,
    costPerUnit: 250, // Rp 250/pc
    supplier: "Eco Cutlery Mandiri",
    lastRestockDate: "23 Sep 2026",
  },
];

// -------------------------------------------------------------------------
// Initial Mock Data: Resep Menu & Bill of Materials (PRD Fase 2)
// -------------------------------------------------------------------------
export const INITIAL_PRODUCT_RECIPES: ProductRecipe[] = [
  {
    productId: "prod-1",
    productName: "Super Mac",
    category: "mac",
    sellingPrice: 20000,
    ingredients: [
      {
        materialId: "rm-1",
        materialName: "Makaroni Elbow Kering",
        amount: 75,
        unit: "gram",
        costPerUnit: 32,
        subtotalCost: 2400,
      },
      {
        materialId: "rm-2",
        materialName: "Keju Cheddar Olahan Melt",
        amount: 30,
        unit: "gram",
        costPerUnit: 98,
        subtotalCost: 2940,
      },
      {
        materialId: "rm-3",
        materialName: "Keju Mozzarella Shredded",
        amount: 15,
        unit: "gram",
        costPerUnit: 135,
        subtotalCost: 2025,
      },
      {
        materialId: "rm-4",
        materialName: "Cooking Cream / Evaporasi",
        amount: 20,
        unit: "ml",
        costPerUnit: 42,
        subtotalCost: 840,
      },
      {
        materialId: "rm-9",
        materialName: "Paper Box MacMood Signature",
        amount: 1,
        unit: "pcs",
        costPerUnit: 850,
        subtotalCost: 850,
      },
      {
        materialId: "rm-10",
        materialName: "Sendok & Garpu Kayu",
        amount: 1,
        unit: "pcs",
        costPerUnit: 250,
        subtotalCost: 250,
      },
    ],
    totalHpp: 9305,
    grossMarginAmount: 10695,
    grossMarginPercent: 53.5,
    maxPortionsAvailable: 193, // min(14500/75, 6800/30, 4200/15, 5500/20, 480/1) = 193
    limitingMaterialName: "Makaroni Elbow Kering",
    notes:
      "Signature recipe creamy comfort mac dengan keju ganda dan aroma gurih seimbang.",
  },
  {
    productId: "prod-2",
    productName: "Potato Mac",
    category: "mac",
    sellingPrice: 15000,
    ingredients: [
      {
        materialId: "rm-1",
        materialName: "Makaroni Elbow Kering",
        amount: 75,
        unit: "gram",
        costPerUnit: 32,
        subtotalCost: 2400,
      },
      {
        materialId: "rm-2",
        materialName: "Keju Cheddar Olahan Melt",
        amount: 30,
        unit: "gram",
        costPerUnit: 98,
        subtotalCost: 2940,
      },
      {
        materialId: "rm-6",
        materialName: "Kentang Fries Frozen",
        amount: 50,
        unit: "gram",
        costPerUnit: 45,
        subtotalCost: 2250,
      },
      {
        materialId: "rm-4",
        materialName: "Cooking Cream / Evaporasi",
        amount: 15,
        unit: "ml",
        costPerUnit: 42,
        subtotalCost: 630,
      },
      {
        materialId: "rm-9",
        materialName: "Paper Box MacMood Signature",
        amount: 1,
        unit: "pcs",
        costPerUnit: 850,
        subtotalCost: 850,
      },
      {
        materialId: "rm-10",
        materialName: "Sendok & Garpu Kayu",
        amount: 1,
        unit: "pcs",
        costPerUnit: 250,
        subtotalCost: 250,
      },
    ],
    totalHpp: 9320,
    grossMarginAmount: 5680,
    grossMarginPercent: 37.9,
    maxPortionsAvailable: 104, // 5200 / 50 = 104 porsi
    limitingMaterialName: "Kentang French Fries Shoestring",
    notes:
      "Kombinasi makaroni keju dengan topping kentang goreng renyah gurih.",
  },
  {
    productId: "prod-3",
    productName: "Classic Mac",
    category: "mac",
    sellingPrice: 10000,
    ingredients: [
      {
        materialId: "rm-1",
        materialName: "Makaroni Elbow Kering",
        amount: 75,
        unit: "gram",
        costPerUnit: 32,
        subtotalCost: 2400,
      },
      {
        materialId: "rm-2",
        materialName: "Keju Cheddar Olahan Melt",
        amount: 25,
        unit: "gram",
        costPerUnit: 98,
        subtotalCost: 2450,
      },
      {
        materialId: "rm-4",
        materialName: "Cooking Cream / Evaporasi",
        amount: 15,
        unit: "ml",
        costPerUnit: 42,
        subtotalCost: 630,
      },
      {
        materialId: "rm-9",
        materialName: "Paper Box MacMood Signature",
        amount: 1,
        unit: "pcs",
        costPerUnit: 850,
        subtotalCost: 850,
      },
      {
        materialId: "rm-10",
        materialName: "Sendok & Garpu Kayu",
        amount: 1,
        unit: "pcs",
        costPerUnit: 250,
        subtotalCost: 250,
      },
    ],
    totalHpp: 6580,
    grossMarginAmount: 3420,
    grossMarginPercent: 34.2,
    maxPortionsAvailable: 193,
    limitingMaterialName: "Makaroni Elbow Kering",
    notes: "Varian original entry-level ramah kantong pelajar.",
  },
  {
    productId: "prod-4",
    productName: "Spicy Smokey Mac",
    category: "mac",
    sellingPrice: 18000,
    ingredients: [
      {
        materialId: "rm-1",
        materialName: "Makaroni Elbow Kering",
        amount: 75,
        unit: "gram",
        costPerUnit: 32,
        subtotalCost: 2400,
      },
      {
        materialId: "rm-2",
        materialName: "Keju Cheddar Olahan Melt",
        amount: 30,
        unit: "gram",
        costPerUnit: 98,
        subtotalCost: 2940,
      },
      {
        materialId: "rm-3",
        materialName: "Keju Mozzarella Shredded",
        amount: 15,
        unit: "gram",
        costPerUnit: 135,
        subtotalCost: 2025,
      },
      {
        materialId: "rm-4",
        materialName: "Cooking Cream / Evaporasi",
        amount: 20,
        unit: "ml",
        costPerUnit: 42,
        subtotalCost: 840,
      },
      {
        materialId: "rm-9",
        materialName: "Paper Box MacMood Signature",
        amount: 1,
        unit: "pcs",
        costPerUnit: 850,
        subtotalCost: 850,
      },
      {
        materialId: "rm-10",
        materialName: "Sendok & Garpu Kayu",
        amount: 1,
        unit: "pcs",
        costPerUnit: 250,
        subtotalCost: 250,
      },
    ],
    totalHpp: 9305,
    grossMarginAmount: 8695,
    grossMarginPercent: 48.3,
    maxPortionsAvailable: 193,
    limitingMaterialName: "Makaroni Elbow Kering",
    notes: "Resep pedas gurih dengan saus keju asap khas.",
  },
  {
    productId: "prod-6",
    productName: "Crispy French Fries",
    category: "sides",
    sellingPrice: 8000,
    ingredients: [
      {
        materialId: "rm-6",
        materialName: "Kentang Fries Frozen",
        amount: 120,
        unit: "gram",
        costPerUnit: 45,
        subtotalCost: 5400,
      },
      {
        materialId: "rm-9",
        materialName: "Paper Box MacMood Signature",
        amount: 1,
        unit: "pcs",
        costPerUnit: 850,
        subtotalCost: 850,
      },
    ],
    totalHpp: 6250,
    grossMarginAmount: 1750,
    grossMarginPercent: 21.9,
    maxPortionsAvailable: 43, // 5200 / 120 = 43 porsi
    limitingMaterialName: "Kentang French Fries Shoestring Frozen",
    notes: "Camilan sampingan kentang goreng krispi.",
  },
  {
    productId: "prod-7",
    productName: "Es Lemon Tea",
    category: "drinks",
    sellingPrice: 6000,
    ingredients: [
      {
        materialId: "rm-7",
        materialName: "Daun Teh Melati Loose",
        amount: 15,
        unit: "gram",
        costPerUnit: 25,
        subtotalCost: 375,
      },
      {
        materialId: "rm-8",
        materialName: "Sari Lemon Murni",
        amount: 25,
        unit: "ml",
        costPerUnit: 35,
        subtotalCost: 875,
      },
      {
        materialId: "rm-9",
        materialName: "Cup Kemasan Dingin + Sedotan",
        amount: 1,
        unit: "pcs",
        costPerUnit: 750,
        subtotalCost: 750,
      },
    ],
    totalHpp: 2000,
    grossMarginAmount: 4000,
    grossMarginPercent: 66.7,
    maxPortionsAvailable: 72, // 1800 / 25 = 72 porsi
    limitingMaterialName: "Sari Lemon Murni Concentrate",
    notes: "Minuman dingin segar dengan margin profit tinggi.",
  },
  {
    productId: "prod-8",
    productName: "Es Teh Manis",
    category: "drinks",
    sellingPrice: 4000,
    ingredients: [
      {
        materialId: "rm-7",
        materialName: "Daun Teh Melati Loose",
        amount: 15,
        unit: "gram",
        costPerUnit: 25,
        subtotalCost: 375,
      },
      {
        materialId: "rm-9",
        materialName: "Cup Kemasan Dingin + Sedotan",
        amount: 1,
        unit: "pcs",
        costPerUnit: 750,
        subtotalCost: 750,
      },
    ],
    totalHpp: 1125,
    grossMarginAmount: 2875,
    grossMarginPercent: 71.9,
    maxPortionsAvailable: 160,
    limitingMaterialName: "Daun Teh Melati Loose",
    notes: "Minuman teh melati manis favorit pelanggan.",
  },
];
