/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as ProtectedAdminRouteImport } from './routes/_protected/admin'
import { Route as ProtectedAppRouteImport } from './routes/_protected/app'
import { Route as ApiAnalyticsIndexRouteImport } from './routes/api/analytics/index'
import { Route as ApiAuditLogsIndexRouteImport } from './routes/api/audit-logs/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiExpensesIndexRouteImport } from './routes/api/expenses/index'
import { Route as ApiNotesIndexRouteImport } from './routes/api/notes/index'
import { Route as ApiNotesIdRouteImport } from './routes/api/notes/$id'
import { Route as ApiPromosIndexRouteImport } from './routes/api/promos/index'
import { Route as ApiPromosValidateRouteImport } from './routes/api/promos/validate'
import { Route as ApiAdminNotesIndexRouteImport } from './routes/api/admin/notes/index'
import { Route as ApiAdminNotesIdRouteImport } from './routes/api/admin/notes/$id'
import { Route as ApiCatalogCategoriesIndexRouteImport } from './routes/api/catalog/categories/index'
import { Route as ApiCatalogProductsIndexRouteImport } from './routes/api/catalog/products/index'
import { Route as ApiInventoryMaterialsIndexRouteImport } from './routes/api/inventory/materials/index'
import { Route as ApiInventoryMaterialsRestockRouteImport } from './routes/api/inventory/materials/restock'
import { Route as ApiInventoryRecipesIndexRouteImport } from './routes/api/inventory/recipes/index'
import { Route as ApiPosOrdersIndexRouteImport } from './routes/api/pos/orders/index'
import { Route as ApiPosOrdersSyncRouteImport } from './routes/api/pos/orders/sync'
import { Route as ApiPosShiftsIndexRouteImport } from './routes/api/pos/shifts/index'
import { Route as ApiPosShiftsCloseRouteImport } from './routes/api/pos/shifts/close'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const ProtectedAdminRoute = ProtectedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAppRoute = ProtectedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiAnalyticsIndexRoute = ApiAnalyticsIndexRouteImport.update({
  id: '/api/analytics/',
  path: '/api/analytics/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuditLogsIndexRoute = ApiAuditLogsIndexRouteImport.update({
  id: '/api/audit-logs/',
  path: '/api/audit-logs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExpensesIndexRoute = ApiExpensesIndexRouteImport.update({
  id: '/api/expenses/',
  path: '/api/expenses/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotesIndexRoute = ApiNotesIndexRouteImport.update({
  id: '/api/notes/',
  path: '/api/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotesIdRoute = ApiNotesIdRouteImport.update({
  id: '/api/notes/$id',
  path: '/api/notes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPromosIndexRoute = ApiPromosIndexRouteImport.update({
  id: '/api/promos/',
  path: '/api/promos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPromosValidateRoute = ApiPromosValidateRouteImport.update({
  id: '/api/promos/validate',
  path: '/api/promos/validate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminNotesIndexRoute = ApiAdminNotesIndexRouteImport.update({
  id: '/api/admin/notes/',
  path: '/api/admin/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminNotesIdRoute = ApiAdminNotesIdRouteImport.update({
  id: '/api/admin/notes/$id',
  path: '/api/admin/notes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalogCategoriesIndexRoute =
  ApiCatalogCategoriesIndexRouteImport.update({
    id: '/api/catalog/categories/',
    path: '/api/catalog/categories/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCatalogProductsIndexRoute = ApiCatalogProductsIndexRouteImport.update({
  id: '/api/catalog/products/',
  path: '/api/catalog/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInventoryMaterialsIndexRoute =
  ApiInventoryMaterialsIndexRouteImport.update({
    id: '/api/inventory/materials/',
    path: '/api/inventory/materials/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInventoryMaterialsRestockRoute =
  ApiInventoryMaterialsRestockRouteImport.update({
    id: '/api/inventory/materials/restock',
    path: '/api/inventory/materials/restock',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInventoryRecipesIndexRoute =
  ApiInventoryRecipesIndexRouteImport.update({
    id: '/api/inventory/recipes/',
    path: '/api/inventory/recipes/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPosOrdersIndexRoute = ApiPosOrdersIndexRouteImport.update({
  id: '/api/pos/orders/',
  path: '/api/pos/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPosOrdersSyncRoute = ApiPosOrdersSyncRouteImport.update({
  id: '/api/pos/orders/sync',
  path: '/api/pos/orders/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPosShiftsIndexRoute = ApiPosShiftsIndexRouteImport.update({
  id: '/api/pos/shifts/',
  path: '/api/pos/shifts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPosShiftsCloseRoute = ApiPosShiftsCloseRouteImport.update({
  id: '/api/pos/shifts/close',
  path: '/api/pos/shifts/close',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/admin': typeof ProtectedAdminRoute
  '/app': typeof ProtectedAppRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/notes/$id': typeof ApiNotesIdRoute
  '/api/promos/validate': typeof ApiPromosValidateRoute
  '/api/analytics/': typeof ApiAnalyticsIndexRoute
  '/api/audit-logs/': typeof ApiAuditLogsIndexRoute
  '/api/expenses/': typeof ApiExpensesIndexRoute
  '/api/notes/': typeof ApiNotesIndexRoute
  '/api/promos/': typeof ApiPromosIndexRoute
  '/api/admin/notes/$id': typeof ApiAdminNotesIdRoute
  '/api/inventory/materials/restock': typeof ApiInventoryMaterialsRestockRoute
  '/api/pos/orders/sync': typeof ApiPosOrdersSyncRoute
  '/api/pos/shifts/close': typeof ApiPosShiftsCloseRoute
  '/api/admin/notes/': typeof ApiAdminNotesIndexRoute
  '/api/catalog/categories/': typeof ApiCatalogCategoriesIndexRoute
  '/api/catalog/products/': typeof ApiCatalogProductsIndexRoute
  '/api/inventory/materials/': typeof ApiInventoryMaterialsIndexRoute
  '/api/inventory/recipes/': typeof ApiInventoryRecipesIndexRoute
  '/api/pos/orders/': typeof ApiPosOrdersIndexRoute
  '/api/pos/shifts/': typeof ApiPosShiftsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/admin': typeof ProtectedAdminRoute
  '/app': typeof ProtectedAppRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/notes/$id': typeof ApiNotesIdRoute
  '/api/promos/validate': typeof ApiPromosValidateRoute
  '/api/analytics': typeof ApiAnalyticsIndexRoute
  '/api/audit-logs': typeof ApiAuditLogsIndexRoute
  '/api/expenses': typeof ApiExpensesIndexRoute
  '/api/notes': typeof ApiNotesIndexRoute
  '/api/promos': typeof ApiPromosIndexRoute
  '/api/admin/notes/$id': typeof ApiAdminNotesIdRoute
  '/api/inventory/materials/restock': typeof ApiInventoryMaterialsRestockRoute
  '/api/pos/orders/sync': typeof ApiPosOrdersSyncRoute
  '/api/pos/shifts/close': typeof ApiPosShiftsCloseRoute
  '/api/admin/notes': typeof ApiAdminNotesIndexRoute
  '/api/catalog/categories': typeof ApiCatalogCategoriesIndexRoute
  '/api/catalog/products': typeof ApiCatalogProductsIndexRoute
  '/api/inventory/materials': typeof ApiInventoryMaterialsIndexRoute
  '/api/inventory/recipes': typeof ApiInventoryRecipesIndexRoute
  '/api/pos/orders': typeof ApiPosOrdersIndexRoute
  '/api/pos/shifts': typeof ApiPosShiftsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_protected/admin': typeof ProtectedAdminRoute
  '/_protected/app': typeof ProtectedAppRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/notes/$id': typeof ApiNotesIdRoute
  '/api/promos/validate': typeof ApiPromosValidateRoute
  '/api/analytics/': typeof ApiAnalyticsIndexRoute
  '/api/audit-logs/': typeof ApiAuditLogsIndexRoute
  '/api/expenses/': typeof ApiExpensesIndexRoute
  '/api/notes/': typeof ApiNotesIndexRoute
  '/api/promos/': typeof ApiPromosIndexRoute
  '/api/admin/notes/$id': typeof ApiAdminNotesIdRoute
  '/api/inventory/materials/restock': typeof ApiInventoryMaterialsRestockRoute
  '/api/pos/orders/sync': typeof ApiPosOrdersSyncRoute
  '/api/pos/shifts/close': typeof ApiPosShiftsCloseRoute
  '/api/admin/notes/': typeof ApiAdminNotesIndexRoute
  '/api/catalog/categories/': typeof ApiCatalogCategoriesIndexRoute
  '/api/catalog/products/': typeof ApiCatalogProductsIndexRoute
  '/api/inventory/materials/': typeof ApiInventoryMaterialsIndexRoute
  '/api/inventory/recipes/': typeof ApiInventoryRecipesIndexRoute
  '/api/pos/orders/': typeof ApiPosOrdersIndexRoute
  '/api/pos/shifts/': typeof ApiPosShiftsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/admin'
    | '/app'
    | '/api/auth/$'
    | '/api/notes/$id'
    | '/api/promos/validate'
    | '/api/analytics/'
    | '/api/audit-logs/'
    | '/api/expenses/'
    | '/api/notes/'
    | '/api/promos/'
    | '/api/admin/notes/$id'
    | '/api/inventory/materials/restock'
    | '/api/pos/orders/sync'
    | '/api/pos/shifts/close'
    | '/api/admin/notes/'
    | '/api/catalog/categories/'
    | '/api/catalog/products/'
    | '/api/inventory/materials/'
    | '/api/inventory/recipes/'
    | '/api/pos/orders/'
    | '/api/pos/shifts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/admin'
    | '/app'
    | '/api/auth/$'
    | '/api/notes/$id'
    | '/api/promos/validate'
    | '/api/analytics'
    | '/api/audit-logs'
    | '/api/expenses'
    | '/api/notes'
    | '/api/promos'
    | '/api/admin/notes/$id'
    | '/api/inventory/materials/restock'
    | '/api/pos/orders/sync'
    | '/api/pos/shifts/close'
    | '/api/admin/notes'
    | '/api/catalog/categories'
    | '/api/catalog/products'
    | '/api/inventory/materials'
    | '/api/inventory/recipes'
    | '/api/pos/orders'
    | '/api/pos/shifts'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_protected'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_protected/admin'
    | '/_protected/app'
    | '/api/auth/$'
    | '/api/notes/$id'
    | '/api/promos/validate'
    | '/api/analytics/'
    | '/api/audit-logs/'
    | '/api/expenses/'
    | '/api/notes/'
    | '/api/promos/'
    | '/api/admin/notes/$id'
    | '/api/inventory/materials/restock'
    | '/api/pos/orders/sync'
    | '/api/pos/shifts/close'
    | '/api/admin/notes/'
    | '/api/catalog/categories/'
    | '/api/catalog/products/'
    | '/api/inventory/materials/'
    | '/api/inventory/recipes/'
    | '/api/pos/orders/'
    | '/api/pos/shifts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiNotesIdRoute: typeof ApiNotesIdRoute
  ApiPromosValidateRoute: typeof ApiPromosValidateRoute
  ApiAnalyticsIndexRoute: typeof ApiAnalyticsIndexRoute
  ApiAuditLogsIndexRoute: typeof ApiAuditLogsIndexRoute
  ApiExpensesIndexRoute: typeof ApiExpensesIndexRoute
  ApiNotesIndexRoute: typeof ApiNotesIndexRoute
  ApiPromosIndexRoute: typeof ApiPromosIndexRoute
  ApiAdminNotesIdRoute: typeof ApiAdminNotesIdRoute
  ApiInventoryMaterialsRestockRoute: typeof ApiInventoryMaterialsRestockRoute
  ApiPosOrdersSyncRoute: typeof ApiPosOrdersSyncRoute
  ApiPosShiftsCloseRoute: typeof ApiPosShiftsCloseRoute
  ApiAdminNotesIndexRoute: typeof ApiAdminNotesIndexRoute
  ApiCatalogCategoriesIndexRoute: typeof ApiCatalogCategoriesIndexRoute
  ApiCatalogProductsIndexRoute: typeof ApiCatalogProductsIndexRoute
  ApiInventoryMaterialsIndexRoute: typeof ApiInventoryMaterialsIndexRoute
  ApiInventoryRecipesIndexRoute: typeof ApiInventoryRecipesIndexRoute
  ApiPosOrdersIndexRoute: typeof ApiPosOrdersIndexRoute
  ApiPosShiftsIndexRoute: typeof ApiPosShiftsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/app': {
      id: '/_protected/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof ProtectedAppRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/analytics/': {
      id: '/api/analytics/'
      path: '/api/analytics'
      fullPath: '/api/analytics/'
      preLoaderRoute: typeof ApiAnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audit-logs/': {
      id: '/api/audit-logs/'
      path: '/api/audit-logs'
      fullPath: '/api/audit-logs/'
      preLoaderRoute: typeof ApiAuditLogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/expenses/': {
      id: '/api/expenses/'
      path: '/api/expenses'
      fullPath: '/api/expenses/'
      preLoaderRoute: typeof ApiExpensesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notes/': {
      id: '/api/notes/'
      path: '/api/notes'
      fullPath: '/api/notes/'
      preLoaderRoute: typeof ApiNotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notes/$id': {
      id: '/api/notes/$id'
      path: '/api/notes/$id'
      fullPath: '/api/notes/$id'
      preLoaderRoute: typeof ApiNotesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/promos/': {
      id: '/api/promos/'
      path: '/api/promos'
      fullPath: '/api/promos/'
      preLoaderRoute: typeof ApiPromosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/promos/validate': {
      id: '/api/promos/validate'
      path: '/api/promos/validate'
      fullPath: '/api/promos/validate'
      preLoaderRoute: typeof ApiPromosValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/notes/': {
      id: '/api/admin/notes/'
      path: '/api/admin/notes'
      fullPath: '/api/admin/notes/'
      preLoaderRoute: typeof ApiAdminNotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/notes/$id': {
      id: '/api/admin/notes/$id'
      path: '/api/admin/notes/$id'
      fullPath: '/api/admin/notes/$id'
      preLoaderRoute: typeof ApiAdminNotesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog/categories/': {
      id: '/api/catalog/categories/'
      path: '/api/catalog/categories'
      fullPath: '/api/catalog/categories/'
      preLoaderRoute: typeof ApiCatalogCategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog/products/': {
      id: '/api/catalog/products/'
      path: '/api/catalog/products'
      fullPath: '/api/catalog/products/'
      preLoaderRoute: typeof ApiCatalogProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inventory/materials/': {
      id: '/api/inventory/materials/'
      path: '/api/inventory/materials'
      fullPath: '/api/inventory/materials/'
      preLoaderRoute: typeof ApiInventoryMaterialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inventory/materials/restock': {
      id: '/api/inventory/materials/restock'
      path: '/api/inventory/materials/restock'
      fullPath: '/api/inventory/materials/restock'
      preLoaderRoute: typeof ApiInventoryMaterialsRestockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inventory/recipes/': {
      id: '/api/inventory/recipes/'
      path: '/api/inventory/recipes'
      fullPath: '/api/inventory/recipes/'
      preLoaderRoute: typeof ApiInventoryRecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pos/orders/': {
      id: '/api/pos/orders/'
      path: '/api/pos/orders'
      fullPath: '/api/pos/orders/'
      preLoaderRoute: typeof ApiPosOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pos/orders/sync': {
      id: '/api/pos/orders/sync'
      path: '/api/pos/orders/sync'
      fullPath: '/api/pos/orders/sync'
      preLoaderRoute: typeof ApiPosOrdersSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pos/shifts/': {
      id: '/api/pos/shifts/'
      path: '/api/pos/shifts'
      fullPath: '/api/pos/shifts/'
      preLoaderRoute: typeof ApiPosShiftsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pos/shifts/close': {
      id: '/api/pos/shifts/close'
      path: '/api/pos/shifts/close'
      fullPath: '/api/pos/shifts/close'
      preLoaderRoute: typeof ApiPosShiftsCloseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedRouteChildren {
  ProtectedAdminRoute: typeof ProtectedAdminRoute
  ProtectedAppRoute: typeof ProtectedAppRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAdminRoute: ProtectedAdminRoute,
  ProtectedAppRoute: ProtectedAppRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiNotesIdRoute: ApiNotesIdRoute,
  ApiPromosValidateRoute: ApiPromosValidateRoute,
  ApiAnalyticsIndexRoute: ApiAnalyticsIndexRoute,
  ApiAuditLogsIndexRoute: ApiAuditLogsIndexRoute,
  ApiExpensesIndexRoute: ApiExpensesIndexRoute,
  ApiNotesIndexRoute: ApiNotesIndexRoute,
  ApiPromosIndexRoute: ApiPromosIndexRoute,
  ApiAdminNotesIdRoute: ApiAdminNotesIdRoute,
  ApiInventoryMaterialsRestockRoute: ApiInventoryMaterialsRestockRoute,
  ApiPosOrdersSyncRoute: ApiPosOrdersSyncRoute,
  ApiPosShiftsCloseRoute: ApiPosShiftsCloseRoute,
  ApiAdminNotesIndexRoute: ApiAdminNotesIndexRoute,
  ApiCatalogCategoriesIndexRoute: ApiCatalogCategoriesIndexRoute,
  ApiCatalogProductsIndexRoute: ApiCatalogProductsIndexRoute,
  ApiInventoryMaterialsIndexRoute: ApiInventoryMaterialsIndexRoute,
  ApiInventoryRecipesIndexRoute: ApiInventoryRecipesIndexRoute,
  ApiPosOrdersIndexRoute: ApiPosOrdersIndexRoute,
  ApiPosShiftsIndexRoute: ApiPosShiftsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
